# Generated by Django 4.2.6 on 2024-02-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_mytaskmodel_completed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='otp_token',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
